# Generated by Django 4.1.2 on 2022-10-28 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpost',
            options={'ordering': ['-date']},
        ),
    ]
