# Generated by Django 4.1.2 on 2022-11-01 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile_profileimg'),
        ('main_app', '0004_post_no_of_likes'),
    ]

    operations = [
    ]
